ui changes
StealthMoney/stealth-web pull request #60
Opened 2024-02-01 05:17 UTC by pablo-clueless

new: dashboard
new: purchase workflow
new: profile and password edit
mod: auth workflow

2024-02-01 08:07 UTC, Extheoisah requested changes
Thanks for opening this for early review. There are a lot of changes related to changes in prettier configuration (the tab spaces most especially). I would suggest we do not change that.

2024-02-01 08:07 UTC, Extheoisah commented on src/components/instant-buy/success.tsx
> +	const viewTxn = () => {
We don't need this function. wrap it in a link that opens a new tab. 
No need to call window

2024-02-01 08:07 UTC, Extheoisah commented on src/components/profile/authentication.tsx
> +						<p className="text-white-300">smsnmicheal@gamil.com</p>
fetch profile details from the backend

2024-02-01 08:07 UTC, Extheoisah commented on src/components/sidebar.tsx
lets delete this file if we no longer need it

2024-02-01 15:17 UTC, pablo-clueless commented on .npmrc
Defines how npm should behave whenever a command is run. For now, I'm just making sure that dependencies of every package is also installed along with it.

2024-02-01 15:44 UTC, pablo-clueless commented on src/app/account/forgot-password/page.tsx
> +								onClick={() => router.back()}
We're sure of the previous page would always be `login`, that's the only place where this page can be accessed.

2024-02-01 15:46 UTC, pablo-clueless commented on src/app/account/forgot-password/page.tsx
> +					<div></div>
The `children` props was not optional, forgot to switch it.

2024-02-01 15:46 UTC, pablo-clueless commented on src/app/account/forgot-password/page.tsx
> +					<div></div>
The `children` props was not optional, forgot to switch it.

2024-02-02 12:57 UTC, pablo-clueless commented on src/app/api/transactions/route.ts
> +	try {
Two requests. If the URL contains a `txn` query string, we check for a transaction by it's ID, else we return all transactions.

2024-02-02 13:18 UTC, pablo-clueless commented on src/app/dashboard/nav-list.tsx
> +		path: "/dashboard/plans",
They all have the same layouts and are only accessible from the dashboard. The other alternative is to create a layout, and reuse wherever needed. It adds more files/folders.

2024-02-02 13:55 UTC, pablo-clueless commented on src/app/dashboard/page.tsx
> +								Exchange rate: 1BTC ={" "}
The function throws an error for something called requestAsyncStorage

2024-02-02 14:19 UTC, pablo-clueless commented on src/components/instant-buy/init.tsx
> +					Exchange rate: 1BTC ={" "}
The function throws an error about something called requestAsyncStorage

2024-02-02 14:29 UTC, pablo-clueless commented on src/components/instant-buy/init.tsx
> +			accountNumber: "988852055355",
The endpoint for getting payment details is throwing errors both here and in Postman.

2024-02-28 03:29 UTC, Extheoisah approved these changes

2024-02-28 03:29 UTC, merged